### ISSUE TITLE
please confirm that IHE's token introspection endpoint doesn't unnecessary break compatibility with SMART's draft.

### ISSUE THREAD

**Issue by isaacvetter** [IHE/ITI.IUA#23] opened 2020-11-10 23:21 UTC
https://github.com/IHE/ITI.IUA/blob/master/IHE_ITI_Suppl_IUA.md#3102-introspect-token

Please confirm that IHE's token introspection endpoint doesn't unnecessary break compatibility with [SMART's draft](https://github.com/HL7/smart-app-launch/pull/306/files).

**Comment by joostreuzel** [comment] 2020-11-11 11:04
duplicate of #22

**Closed by joostreuzel** 2020-11-11 11:04 UTC
